### ISSUE TITLE
improve database configuration

### ISSUE THREAD

**Issue by giddel** [markphelps/flipt#316]
I'm very happy for the Mysql support - thanks a lot!
As a little improvement I would suggest to split the configuration of the database credentials into separate keys in the config.yaml e.g.

```
    database:
        name:  flipt
        user: fliptuser
        password: very_secret
        host: localhost
        port: 3306
        protocol: mysql
```
And then build the connection string in the application itself based on these credentials.
So the user does not need to know the internals about the format of the connection string and the configuration is much more easier to understand.
We are using Flipt within a k8s cluster and manage the configuration of the credentials in an encrypted repository. At now I have once to encrypt the whole database connection string for the application and twice the credentials itself separately again  for creating the database itself by the deployment job. This is not usual.
